### ISSUE TITLE
连接空库，注册用户报错

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-project-saas#134]
TypeError: Cannot read property '_id' of undefined
    at Object.Creator.addSpaceUsers (/Users/steedos/Documents/GitHub/steedos-project-saas/node_modules/@steedos/standard-objects/spaces.object.js:96:36)
    at Object.<anonymous> (/Users/steedos/Documents/GitHub/steedos-project-saas/node_modules/@steedos/accounts/src/rest-express/endpoints/steedos/verify_code.ts:378:25)
    at step (/Users/steedos/Documents/GitHub/steedos-project-saas/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/steedos/Documents/GitHub/steedos-project-saas/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/Users/steedos/Documents/GitHub/steedos-project-saas/node_modules/tslib/tslib.js:107:62)
    at /Users/steedos/Documents/GitHub/steedos-project-saas/node_modules/meteor-promise/fiber_pool.js:43:39

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-accounts/issues/81
